
site_name: Prompt Engineering Journal
site_author: Amal N K

# site_url: https://Amal-nellanhi.github.io/prompt-engineering-journal/
use_directory_urls: false

markdown_extensions:
  - attr_list
  - md_in_html
  - toc: 
        permalink: true
        separator: "-"
        toc_depth: 3

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - toc.follow
    

nav:
  - Objective & Structure: 'index.md'
  - About the Researcher: 'researcher.md'
  - Projects:
    - 'P1: Instruction Prompts': 'project-1.md'
    - 'P2: Role-based Prompts': 'project-2.md'
    - 'P3: Text-to-Image Bias & Representation': 'project-3.md'
    - 'P4: Chain-of-Thought Prompts': 'project-4.md'
    - 'P5: Context Bleed & Hallucinations': 'project-5.md'
  - Evaluation Criteria: 'evaluation-criteria.md'
